#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PARAMS_DIR="${LITE_WALLET_ZCASH_PARAMS_DIR:-$ROOT_DIR/src-tauri/resources/zcash-params}"
ENV_FILE="${LITE_WALLET_ZCASH_PARAMS_ENV_FILE:-$ROOT_DIR/.env.zcash-params}"
FORCE_DOWNLOAD="${LITE_WALLET_ZCASH_PARAMS_FORCE:-0}"

SPEND_FILE="sapling-spend.params"
OUTPUT_FILE="sapling-output.params"
SPEND_URL="https://download.z.cash/downloads/${SPEND_FILE}"
OUTPUT_URL="https://download.z.cash/downloads/${OUTPUT_FILE}"

SPEND_MIN_BYTES=40000000
OUTPUT_MIN_BYTES=3000000

require_cmd() {
  local name="$1"
  if ! command -v "$name" >/dev/null 2>&1; then
    echo "[zcash-params] Missing required command: $name" >&2
    exit 1
  fi
}

sha256_of_file() {
  local path="$1"
  shasum -a 256 "$path" | awk '{print tolower($1)}'
}

is_placeholder_file() {
  local path="$1"
  local min_bytes="$2"

  if [[ ! -f "$path" ]]; then
    return 0
  fi

  local size
  size="$(wc -c <"$path" | tr -d '[:space:]')"
  if [[ -z "$size" || "$size" -lt "$min_bytes" ]]; then
    return 0
  fi

  if LC_ALL=C head -c 8192 "$path" | tr '[:upper:]' '[:lower:]' | grep -q "placeholder"; then
    return 0
  fi

  return 1
}

download_file() {
  local url="$1"
  local target="$2"

  echo "[zcash-params] Downloading $(basename "$target")..."
  local tmp="${target}.tmp"
  rm -f "$tmp"

  curl -fL --retry 5 --retry-delay 2 --connect-timeout 10 --max-time 300 "$url" -o "$tmp"
  mv "$tmp" "$target"
}

require_cmd curl
require_cmd shasum

mkdir -p "$PARAMS_DIR"

SPEND_PATH="$PARAMS_DIR/$SPEND_FILE"
OUTPUT_PATH="$PARAMS_DIR/$OUTPUT_FILE"

if [[ "$FORCE_DOWNLOAD" == "1" ]] || is_placeholder_file "$SPEND_PATH" "$SPEND_MIN_BYTES"; then
  download_file "$SPEND_URL" "$SPEND_PATH"
else
  echo "[zcash-params] Reusing existing $SPEND_FILE"
fi

if [[ "$FORCE_DOWNLOAD" == "1" ]] || is_placeholder_file "$OUTPUT_PATH" "$OUTPUT_MIN_BYTES"; then
  download_file "$OUTPUT_URL" "$OUTPUT_PATH"
else
  echo "[zcash-params] Reusing existing $OUTPUT_FILE"
fi

if is_placeholder_file "$SPEND_PATH" "$SPEND_MIN_BYTES"; then
  echo "[zcash-params] Spend params failed placeholder/size sanity check." >&2
  exit 1
fi

if is_placeholder_file "$OUTPUT_PATH" "$OUTPUT_MIN_BYTES"; then
  echo "[zcash-params] Output params failed placeholder/size sanity check." >&2
  exit 1
fi

SPEND_SHA256="$(sha256_of_file "$SPEND_PATH")"
OUTPUT_SHA256="$(sha256_of_file "$OUTPUT_PATH")"

cat >"$ENV_FILE" <<ENVVARS
# Generated by scripts/bootstrap-zcash-params.sh
LITE_WALLET_ZCASH_PARAMS_DIR=$PARAMS_DIR
LITE_WALLET_SAPLING_SPEND_PARAMS_SHA256=$SPEND_SHA256
LITE_WALLET_SAPLING_OUTPUT_PARAMS_SHA256=$OUTPUT_SHA256
ENVVARS

echo "[zcash-params] Wrote checksums to $ENV_FILE"
echo "[zcash-params] Spend sha256:  $SPEND_SHA256"
echo "[zcash-params] Output sha256: $OUTPUT_SHA256"

"$ROOT_DIR/scripts/check-zcash-params.sh"
